import { isOverdue } from "./store";
import type { Item } from "./types";
import { daysInProgress, isEscalated, STATUS_LABEL, TYPE_LABEL } from "./types";

export function buildReportHtml({ title, project, company, preparedBy, isClosed, items }: { title: string; project: string; company: string; preparedBy: string; isClosed: boolean; items: Item[] }) {
  const open = items.filter((i) => i.status !== "closed" && i.status !== "complete").length;
  const closed = items.length - open;
  const overdue = items.filter(isOverdue).length;
  const escalated = items.filter(isEscalated).length;
  const date = new Date().toLocaleString();
  const groups = groupByBuildingLevel(items);
  const outstanding = items.filter((i) => i.status === "rejected");

  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)} — ${escapeHtml(project)}</title>${styleBlock(isClosed)}</head><body><header><div><div class="brand">CleanRun IQ<small>${escapeHtml(company || "The smarter way to a clean handover")}</small></div></div><div class="meta"><h1>${escapeHtml(title)}</h1><div><b>${escapeHtml(project)}</b></div><div>Generated ${escapeHtml(date)}</div>${preparedBy ? `<div>Prepared by <b>${escapeHtml(preparedBy)}</b></div>` : ""}</div></header><div class="stats"><div class="stat"><span>Total</span><b>${items.length}</b></div><div class="stat"><span>Open</span><b>${open}</b></div><div class="stat"><span>Closed</span><b>${closed}</b></div><div class="stat"><span>Overdue</span><b>${overdue}</b></div><div class="stat"><span>Escalated 10d+</span><b>${escalated}</b></div></div>${groups.length === 0 ? `<p class="meta" style="margin-top:20px">No items in scope for this report.</p>` : ""}${groups.map((g) => renderGroup(g, isClosed)).join("")}${renderOutstanding(outstanding)}<footer><span>Generated by CleanRun IQ${company ? ` · ${escapeHtml(company)}` : ""}</span><span>${escapeHtml(date)}</span></footer></body></html>`;
}

function styleBlock(isClosed: boolean) {
  return `<style>@page{margin:12mm;size:A4 landscape}*{box-sizing:border-box}body{font-family:-apple-system,Inter,system-ui,sans-serif;color:#0f172a;font-size:10.5px;line-height:1.4}header{display:flex;justify-content:space-between;border-bottom:2px solid #0f172a;padding-bottom:10px;margin-bottom:14px}.brand{font-weight:800;font-size:18px}.brand small{display:block;font-weight:500;font-size:10px;color:#64748b}.meta{color:#64748b;font-size:10px;text-align:right}.meta b{color:#0f172a}h1{font-size:18px;margin:0 0 2px}h2.building{font-size:13px;margin:18px 0 4px;padding:7px 10px;background:#0f172a;color:#fff;border-radius:6px}h3.level{font-size:10.5px;margin:10px 0 4px;padding:4px 8px;background:#e2e8f0;border-radius:4px;text-transform:uppercase;letter-spacing:.06em}.stats{display:flex;gap:8px;margin:8px 0}.stat{flex:1;border:1px solid #e2e8f0;border-radius:8px;padding:8px 10px}.stat b{font-size:18px;display:block}.stat span{color:#64748b;font-size:9px;text-transform:uppercase}table{width:100%;border-collapse:collapse;table-layout:fixed}th{background:#f8fafc;text-align:left;font-size:9.5px;text-transform:uppercase;color:#475569;padding:6px;border-bottom:1px solid #cbd5e1}td{padding:8px 6px;border-bottom:1px solid #e2e8f0;vertical-align:top}tr.escalated td{background:#fef2f2}tr.closed td{background:#f0fdf4}.code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-weight:700}.loc-b{font-weight:600}.loc-m,.signoff{color:#64748b;font-size:9px}.status{display:inline-block;padding:1px 7px;border-radius:999px;font-size:9px;font-weight:600;background:#e2e8f0}.status.closed{background:#dcfce7;color:#166534}.status.issued{background:#dbeafe;color:#1e40af}.status.progress{background:#fef3c7;color:#92400e}.status.review{background:#ede9fe;color:#5b21b6}.status.rejected{background:#fee2e2;color:#991b1b}.pill{display:inline-block;padding:1px 6px;border-radius:999px;font-size:8.5px;font-weight:700;text-transform:uppercase;margin-right:2px}.pill.high{background:#fef3c7;color:#92400e}.pill.urgent{background:#fee2e2;color:#991b1b}.pill.over,.pill.esc{background:#dc2626;color:#fff}.photos{display:flex;flex-wrap:wrap;gap:2px}.photos img{width:44px;height:34px;object-fit:cover;border-radius:3px;border:1px solid #e2e8f0}.ev-col h5{margin:0 0 3px;font-size:8.5px;text-transform:uppercase;color:#64748b}.empty{font-size:8.5px;color:#94a3b8;font-style:italic}.ready{color:#166534;font-weight:600}.signoff-box{border:1px dashed #cbd5e1;border-radius:4px;padding:6px;text-align:center;font-size:9px;color:#64748b}.line{border-top:1px solid #94a3b8;margin-top:18px;padding-top:2px}footer{margin-top:18px;padding-top:8px;border-top:1px solid #e2e8f0;font-size:9px;color:#94a3b8;display:flex;justify-content:space-between}.outstanding{margin-top:20px;border:1px solid #fecaca;background:#fff7f7;padding:10px 12px;border-radius:8px}.outstanding h3{margin:0 0 6px;font-size:12px;color:#991b1b}col.c-code{width:6%}col.c-loc{width:12%}col.c-stat{width:11%}col.c-orig{width:${isClosed ? "12%" : "15%"}}col.c-rect{width:${isClosed ? "12%" : "0%"}}col.c-clos{width:${isClosed ? "12%" : "0%"}}col.c-desc{width:${isClosed ? "17%" : "30%"}}col.c-resp{width:12%}col.c-sig{width:${isClosed ? "6%" : "14%"}}</style>`;
}

function renderOutstanding(items: Item[]) {
  if (items.length === 0) return "";
  return `<div class="outstanding"><h3>Outstanding — rejected items requiring re-issue (${items.length})</h3><ul>${items.map((i) => `<li><b>${escapeHtml(i.code)}</b> · ${escapeHtml(i.building)} ${escapeHtml(i.unit)} · ${escapeHtml(i.subcontractor || "Unassigned")} — ${escapeHtml(i.rejectionReason ?? "Rejected on inspection")}</li>`).join("")}</ul></div>`;
}

function groupByBuildingLevel(items: Item[]): Array<{ building: string; levels: Array<{ level: string; items: Item[] }> }> {
  const buildings = new Map<string, Map<string, Item[]>>();
  for (const item of items) {
    const building = item.building || "Unassigned";
    const level = item.level || "—";
    if (!buildings.has(building)) buildings.set(building, new Map());
    const levels = buildings.get(building)!;
    if (!levels.has(level)) levels.set(level, []);
    levels.get(level)!.push(item);
  }
  return Array.from(buildings.keys()).sort().map((building) => ({
    building,
    levels: Array.from(buildings.get(building)!.keys()).sort().map((level) => ({
      level,
      items: buildings.get(building)!.get(level)!.slice().sort((a, b) => a.code.localeCompare(b.code)),
    })),
  }));
}

function renderGroup(group: { building: string; levels: Array<{ level: string; items: Item[] }> }, isClosed: boolean) {
  return `<h2 class="building">${escapeHtml(group.building)} <span style="opacity:.7;font-weight:500;font-size:11px">· ${group.levels.reduce((a, l) => a + l.items.length, 0)} item(s)</span></h2>${group.levels.map((level) => `<h3 class="level">${escapeHtml(level.level)} · ${level.items.length} item(s)</h3><table><colgroup><col class="c-code"/><col class="c-loc"/><col class="c-stat"/><col class="c-orig"/>${isClosed ? `<col class="c-rect"/><col class="c-clos"/>` : ""}<col class="c-desc"/><col class="c-resp"/><col class="c-sig"/></colgroup><thead><tr><th>Defect #</th><th>Location</th><th>Status / Issued</th><th>${isClosed ? "Original" : "Photos"}</th>${isClosed ? "<th>Rectification</th><th>Closeout</th>" : ""}<th>Description</th><th>Responsible</th><th>Sign-off</th></tr></thead><tbody>${level.items.map((item) => renderRow(item, isClosed)).join("")}</tbody></table>`).join("")}`;
}

function renderPhotos(photos: Array<string | undefined>, empty: string) {
  const valid = photos.filter((photo): photo is string => !!photo);
  return valid.length ? `<div class="photos">${valid.slice(0, 3).map((photo) => `<img src="${escapeHtml(photo)}" alt="" />`).join("")}</div>` : `<div class="empty">${escapeHtml(empty)}</div>`;
}

function statusClass(status: string): string {
  if (status === "closed" || status === "complete") return "closed";
  if (status === "issued") return "issued";
  if (status === "in_progress") return "progress";
  if (status === "ready_for_review" || status === "under_inspection") return "review";
  if (status === "rejected") return "rejected";
  return "";
}

function renderRow(item: Item, isClosed: boolean): string {
  const closed = item.status === "closed" || item.status === "complete";
  const escalated = isEscalated(item);
  const overdue = isOverdue(item);
  const issued = item.issuedAt ? new Date(item.issuedAt).toLocaleDateString() : "—";
  const inProgress = daysInProgress(item);
  const firstCloseout = item.closeoutEvidence[0];
  const signoff = closed && firstCloseout ? `<div class="signoff ready">✓ ${item.status === "complete" ? "Complete" : "Closed"}</div><div class="signoff"><b>${escapeHtml(firstCloseout.by)}</b><br/>${escapeHtml(firstCloseout.role)}</div><div class="signoff">${new Date(firstCloseout.at).toLocaleDateString()}</div>` : item.status === "ready_for_review" || item.status === "under_inspection" ? `<div class="signoff ready">Inspection</div><div class="signoff-box"><div class="line">Signature</div></div>` : `<div class="signoff-box"><div class="line">Pending</div></div>`;
  const rectCol = isClosed ? `<td class="ev-col"><h5>Subcontractor rectification</h5>${renderPhotos(item.rectificationEvidence.map((e) => e.photo), "No photo attached")}${item.rectificationEvidence[0]?.comment ? `<div class="signoff">${escapeHtml(item.rectificationEvidence[0].comment)}</div>` : ""}${item.rectificationEvidence[0]?.by ? `<div class="signoff">${escapeHtml(item.rectificationEvidence[0].by)}</div>` : ""}</td>` : "";
  const closeEmpty = item.type === "incomplete" && item.status === "complete" ? "Completed without photo evidence" : "No photo attached";
  const closeCol = isClosed ? `<td class="ev-col"><h5>Closeout evidence</h5>${renderPhotos(item.closeoutEvidence.map((e) => e.photo), closeEmpty)}${firstCloseout?.note ? `<div class="signoff">${escapeHtml(firstCloseout.note)}</div>` : ""}</td>` : "";
  return `<tr class="${escalated ? "escalated" : closed ? "closed" : ""}"><td><span class="code">${escapeHtml(item.code)}</span><div class="loc-m">${escapeHtml(TYPE_LABEL[item.type])}</div></td><td><div class="loc-b">${escapeHtml(item.unit || "—")}</div><div class="loc-m">${escapeHtml(item.room || "")}</div><div class="loc-m">${escapeHtml(item.building)} · ${escapeHtml(item.level)}</div>${item.raisedBy ? `<div class="loc-m">Raised: ${escapeHtml(item.raisedBy)}</div>` : ""}</td><td><span class="status ${statusClass(item.status)}">${escapeHtml(STATUS_LABEL[item.status])}</span><div class="loc-m" style="margin-top:4px">Issued: ${escapeHtml(issued)}</div><div class="loc-m">Due: ${escapeHtml(item.dueDate)}</div><div style="margin-top:4px"><span class="pill ${item.priority}">${escapeHtml(item.priority)}</span>${overdue ? `<span class="pill over">Overdue</span>` : ""}${escalated ? `<span class="pill esc">Esc ${inProgress}d</span>` : ""}</div></td><td class="ev-col"><h5>Original issue evidence</h5>${renderPhotos(item.originalPhotos, "No photo attached")}</td>${rectCol}${closeCol}<td>${escapeHtml(item.description)}${item.rejectionReason ? `<div class="signoff" style="color:#991b1b;margin-top:4px">Rejected: ${escapeHtml(item.rejectionReason)}</div>` : ""}${item.closeoutEvidence.length > 1 ? `<div class="signoff">Previous closeout entries retained: ${item.closeoutEvidence.length}</div>` : ""}</td><td><div style="font-weight:600">${escapeHtml(item.subcontractor || "Unassigned")}</div><div class="loc-m">${escapeHtml(item.trade || "")}</div></td><td>${signoff}</td></tr>`;
}

function escapeHtml(value: string) {
  return (value ?? "").replace(/[&<>"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char]!));
}
