services:
  - type: web
    name: cleanrun-iq
    env: node
    plan: free
    buildCommand: NITRO_PRESET=node-server npm install && NITRO_PRESET=node-server npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: NITRO_PRESET
        value: node-server
